version: "3.7"
services:
     cypress-integration: 
          build: .
          image: cypress_custom_image:v8.2.0
          user: root
          volumes:
               - $PWD:/cypress_demo
          command: 
               - /bin/bash
               - -c
               - |
                    echo "Running Tests"
                    npm install

                    if npm test ; then
                         echo "=====Test Succeeded======="
                         npm run generate-report

                    else
                         echo "=====Test Failed========"
                         npm run generate-report
                         exit 1
                    fi